# _quarto.yml content
project:
  type: website
  output-dir: docs

website:
  title: "GERAD: Tutoriel Ti*k*Z"
  navbar:
    left:
      - text: "Exemple 1"
        href: 01-BasicExample/quarto/main.html
      - text: "Exemple 2"
        href: 02-BasicExample/quarto/main.html
      - text: "Mouvement de projectile"
        href: 03-ProjectileMotion/quarto/main.html